---
apiVersion: v1
kind: Service
metadata:
  name: flamecord-service
spec:
  selector:
    app: flamecord
  type: NodePort
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: 30000 # you can choose another port between 30000-32767 if desired
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: flamecord-nodeport
#spec:
#  type: NodePort
#  selector:
#    app: flamecord
#  ports:
#    - port: 25565
#      targetPort: 25565
#      nodePort: 32767
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flamecord
spec:
  selector:
    matchLabels:
      app: flamecord
  template:
    metadata:
      labels:
        app: flamecord
    spec:
      containers:
      - name: flamecord
        image: registry.theflyingbirds.net/flamecord:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 25565
      imagePullSecrets:
      - name: regcred