apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby
spec:
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      containers:
      - name: lobby
        image: registry.theflyingbirds.net/lobby:latest
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 25566
      imagePullSecrets:
      - name: regcred