apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: minecraft-server
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: minecraft
          image: minecraft:latest
          ports:
            - containerPort: 25565
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30000
  selector:
    app: minecraft-server
